[all_systems]
SCNPC-013 ansible_host=192.168.3.20 os_type=Windows

[all_systems:vars]
ansible_user=admin
ansible_password='scn!2122'
ansible_port=5986
ansible_connection=winrm
ansible_winrm_server_cert_validation=ignore
ansible_winrm_transport=ntlm
